NANITE_MAX_CLUSTER_TRIANGLES = 128
NANITE_MAX_CLUSTER_VERTICES = 256
NANITE_MAX_CLUSTER_INDICES = 384
NANITE_MAX_UVS = 4
NANITE_FIXUP_MAGIC = b'NF'
NANITE_STREAMING_PAGE_GPU_SIZE = 131072
NANITE_MAX_CLUSTERS_PER_PAGE = 256
NANITE_MAX_TRANSCODE_GROUPS_PER_PAGE = 128
NANITE_MIN_POSITION_PRECISION = -8
NANITE_MAX_NORMAL_QUANTIZATION_BITS = 15
NANITE_MAX_TANGENT_QUANTIZATION_BITS = 12
NANITE_MAX_TEXCOORD_QUANTIZATION_BITS = 15
NANITE_MAX_COLOR_QUANTIZATION_BITS = 8
NANITE_MAX_CLUSTERS_PER_PAGE_BITS = 8

NANITE_MAX_ATTRIBUTE_BITS = [
	2 * NANITE_MAX_NORMAL_QUANTIZATION_BITS \
	+ 1 + NANITE_MAX_TANGENT_QUANTIZATION_BITS \
	+ 4 * NANITE_MAX_COLOR_QUANTIZATION_BITS \
	+ NumTexCoordInterpolators * (2 * NANITE_MAX_TEXCOORD_QUANTIZATION_BITS)
	for NumTexCoordInterpolators in range(0, NANITE_MAX_UVS + 1)
]